//------------------------------------------------------------------------------
// GENERATED CODE - DO NOT MODIFY
//------------------------------------------------------------------------------
// This file was auto-generated by the GameMaker Studio 2 Scene Exporter
// export_scene_header.gml
// Generator version: 1.0.0
// Generated: 2026-05-02 13:45:12 UTC
// Source project: MyGame.gmx / MyGame.yyp
// Input: rm_level_01
//
// Manual edits will be overwritten the next time the exporter runs.
//------------------------------------------------------------------------------

#ifndef SCENE_DATA_H
#define SCENE_DATA_H

#define SCENE_WIDTH 1440
#define SCENE_HEIGHT 880

#define GRID_WIDTH 18
#define GRID_HEIGHT 11

#define CELL_WIDTH 80
#define CELL_HEIGHT 80

#define NUM_PREFABS 4 
#define NUM_ENTS    22 
#define NUM_PHYS    2
#define NUM_ANIM    2
#define NUM_SPR     1
#define NUM_CAMS    1
#define NUM_TILES   37
#define NUM_STATS   4 
#define NUM_FORCES  4

#define NUM_RELATE 2 

#include "game_import.h"

typedef struct {
    const char* engine_instance;
		const char* prefab;
    EntityType  type;
    float x;
    float y;
} EntityInstance;

static const EntityPrefab PREFAB_DATA[NUM_PREFABS] = {
  {"level",  1, {"Level"}},
  {"camera", 2, {"Camera", "Track"}},
  {"player", 6, 
    {"Follow", "Animation", "Position", "Input", "Physics", "Type"},
  },
  {"slime", 4, 
    {"Animation", "Position", "Physics", "Type"},
  },
  //{"floor",   3, {"Sprite", "Position", "Type"}},
};



static const EntityRelations ENT_RELATE[NUM_RELATE] = {
  {"player", 2,
    { 
      {"Force", 2, 
        {
          {"player-steering", REL_AppliesTo},
          {"player-bump", REL_AppliesTo},
        }
      },
      {"Stat", 2,
        {
          {"player-hp", REL_AppliesTo},
          {"player-dmg", REL_AppliesTo},

        }
      }
    }
  },
  {"slime", 2,
    { 
      {"Force", 2, 
        {
          {"slime-steering", REL_AppliesTo},
          {"slime-bump", REL_AppliesTo},
        },
      },
      {"Stat", 2,
        {
          {"slime-hp", REL_AppliesTo},
          {"slime-dmg", REL_AppliesTo},
        }
      }
    }
  }
};

static const EntityInstance ENT_DATA[NUM_ENTS] = {
    {"ent_data", "level", ENT_OMNI, 0, 0},
    {"ent_data", "camera", ENT_OMNI, 128, 128},
    {"ent_data", "player", ENT_PLAYER, 128, 128},
    {"ent_data", "slime", ENT_MOB, 416, 288},
    {"ent_data", "slime", ENT_MOB, 460, 288},
    {"ent_data", "slime", ENT_MOB, 416, 88},
    {"ent_data", "slime", ENT_MOB, 416, 308},
    {"ent_data", "slime", ENT_MOB, 300, 288},
    {"ent_data", "slime", ENT_MOB, 46, 288},
    {"ent_data", "slime", ENT_MOB, 416, 28},
    {"ent_data", "slime", ENT_MOB, 146, 88},
    {"ent_data", "slime", ENT_MOB, 246, 88},
    {"ent_data", "slime", ENT_MOB, 346, 88},
    {"ent_data", "slime", ENT_MOB, 46, 188},
    {"ent_data", "slime", ENT_MOB, 46, 388},
    {"ent_data", "slime", ENT_MOB, 46, 488},
    {"ent_data", "slime", ENT_MOB, 146, 388},
    {"ent_data", "slime", ENT_MOB, 346, 388},
    {"ent_data", "slime", ENT_MOB, 446, 388},
    {"ent_data", "slime", ENT_MOB, 6, 88},
    {"ent_data", "slime", ENT_MOB, 6, 88},
    {"ent_data", "slime", ENT_MOB, 6, 88},
};

// Tile Data
typedef struct {
    int tile_index;
    int prefab_index;
    int start_x;
		int start_y;
		int map_x;
    int map_y;
    int rotation;
    bool flip_x;
    bool flip_y;
} TileInstance;

static const phys_d PHYS_DATA[NUM_PHYS] = {
  {"player",  SHAPE_CIRCLE, 10, 8},
  {"slime",   SHAPE_CIRCLE, 8, 8},
};

static const force_d FORCE_DATA[NUM_FORCES] = {
  {"player-steering", FORCE_STEERING,
    0.67f, 2.45f, 0.067f, {0.69, 0.69},
    PHYS_EVENT_ACCEL,
  },
  {"slime-steering", FORCE_STEERING,
    1.0f, 1.75f, 0.125f, {0.65, 0.67},
    PHYS_EVENT_ACCEL,
  },
  {"player-bump", FORCE_IMPULSE,
    0.5f, 1.25f, 0.1f, {0.85, 0.75},
    PHYS_EVENT_COLL, REACT_BUMP
  },
  {"slime-bump", FORCE_IMPULSE,
    0.34f, 1.15f, 0.125f, {0.85, 0.67},
    PHYS_EVENT_COLL, REACT_BUMP
  },

};

static const stat_d STAT_DATA[NUM_STATS] = {
  {"player-hp", STAT_HP, 0, 25, 25},
  {"player-dmg", STAT_DMG, 1, 1, 1},
  {"slime-hp", STAT_HP, 0, 10, 10},
  {"slime-dmg", STAT_DMG, 1, 1, 1},
};

static const anim_d ANIM_DATA[NUM_ANIM] = {
  {"player",  SHEET_CHAR,
    {
      {
        {ANIM_WALK, "walk0", 0, false, ANIM_SUSPEND},
        {ANIM_WALK, "walk90", 90, false, ANIM_SUSPEND},
        {ANIM_WALK, "walk180", 180, false, ANIM_SUSPEND},
        {ANIM_WALK, "walk270", 270, false, ANIM_SUSPEND},
      },
      {
        {ANIM_IDLE, "idle0", 0, true, },
        {ANIM_IDLE, "idle90", 90, true, },
        {ANIM_IDLE, "idle180", 180, true, },
        {ANIM_IDLE, "idle270", 270, true, },
      },
      {
        {ANIM_ATTACK, "attack0", 0, false, ANIM_SUSPEND, ANIM_HURTBOX},
        {ANIM_ATTACK, "attack90", 90, false, ANIM_SUSPEND, ANIM_HURTBOX},
        {ANIM_ATTACK, "attack180", 180, false, ANIM_SUSPEND, ANIM_HURTBOX},
        {ANIM_ATTACK, "attack270", 270, false, ANIM_SUSPEND, ANIM_HURTBOX},
      }
    }
  },
  {"slime",   SHEET_MOB,
    {
      { 
        {ANIM_WALK, "walk0", 0, false, ANIM_SUSPEND},
        {ANIM_WALK, "walk90", 90, false, ANIM_SUSPEND},
        {ANIM_WALK, "walk180", 180, false, ANIM_SUSPEND},
        {ANIM_WALK, "walk270", 270, false, ANIM_SUSPEND},
      },
      {
        {ANIM_HURT, "hurt0", 0, false, ANIM_SUSPEND},
        {ANIM_HURT, "hurt90", 90, false, ANIM_SUSPEND},
        {ANIM_HURT, "hurt180", 180, false, ANIM_SUSPEND},
        {ANIM_HURT, "hurt270", 270, false, ANIM_SUSPEND},
      },
      {
        {ANIM_IDLE, "idle0", 0, true, },
        {ANIM_IDLE, "idle90", 90, true, },
        {ANIM_IDLE, "idle180", 180, true, },
        {ANIM_IDLE, "idle270", 270, true, },
      },
    }
  }
};

static const cam_d CAM_DATA[NUM_CAMS] = {
  {"camera", 3.f, 0.f, 800, 600, 1600, 1200, 264, 200, 272, 254}
};

static const sprite_d SPR_DATA[NUM_SPR] = {

};


static const TileInstance scene_tiles[NUM_TILES] = {
    {4,	4, 0, 0, 0, 0, 0, 0, 0},
    {4,	4, 0, 240, 0, 3, 0, 0, 0},
    {6,	4, 0, 320, 0, 4, 0, 0, 0},
    {5,	4, 0, 400, 0, 5, 0, 0, 0},
    {4,	4, 0, 480, 0, 6, 0, 0, 0},
    {6,	4, 0, 560, 0, 7, 0, 0, 0},
    {5,	4, 0, 640, 0, 8, 0, 0, 0},
    {5,	4, 80, 0, 1, 0, 0, 0, 0},
    {4,	4, 160, 800, 2, 10, 0, 0, 0},
    {6,	4, 240, 800, 3, 10, 0, 0, 0},
    {5,	4, 320, 0, 4, 0, 0, 0, 0},
    {5,	4, 320, 800, 4, 10, 0, 0, 0},
    {6,	4, 400, 0, 5, 0, 0, 0, 0},
    {4,	4, 400, 800, 5, 10, 0, 0, 0},
    {4,	4, 480, 0, 6, 0, 0, 0, 0},
    {5,	4, 560, 0, 7, 0, 0, 0, 0},
    {6,	4, 640, 0, 8, 0, 0, 0, 0},
    {4,	4, 640, 800, 8, 10, 0, 0, 0},
    {6,	4, 720, 800, 9, 10, 0, 0, 0},
    {5,	4, 800, 800, 10, 10, 0, 0, 0},
    {4,	4, 880, 800, 11, 10, 0, 0, 0},
    {4,	4, 960, 0, 12, 0, 0, 0, 0},
    {6,	4, 960, 800, 12, 10, 0, 0, 0},
    {5,	4, 1040, 0, 13, 0, 0, 0, 0},
    {5,	4, 1040, 800, 13, 10, 0, 0, 0},
    {6,	4, 1120, 0, 14, 0, 0, 0, 0},
    {4,	4, 1120, 800, 14, 10, 0, 0, 0},
    {4,	4, 1200, 0, 15, 0, 0, 0, 0},
    {6,	4, 1200, 800, 15, 10, 0, 0, 0},
    {5,	4, 1280, 0, 16, 0, 0, 0, 0},
    {6,	4, 1360, 0, 17, 0, 0, 0, 0},
    {6,	4, 1360, 80, 17, 1, 0, 0, 0},
    {5,	4, 1360, 160, 17, 2, 0, 0, 0},
    {4,	4, 1360, 480, 17, 6, 0, 0, 0},
    {6,	4, 1360, 560, 17, 7, 0, 0, 0},
    {4,	4, 1360, 720, 17, 9, 0, 0, 0},
    {4,	4, 1360, 800, 17, 10, 0, 0, 0},
};

void AnimationImport(void*,const char*);
void SpriteImport(void*,const char*);
void PhysicsImport(void*,const char*);
void InputImport(void*,const char*);
void PositionImport(void*,const char*);
void CameraImport(void*,const char*);
void TrackingImport(void*,const char*);
void TypeImport(void* c,const char* name);
void StatImport(void* c,const char* name);
void ForceImport(void* c,const char* name);

static void LevelImport(void* c, const char* name){
  lvl_comp_t* lc = c;

  lc->wid = 800;
  lc->hei = 600;
}

static EntityRelations GetRelationData(const char* name){
  for (int i = 0; i < NUM_RELATE; i++){
    if(strcmp(name, ENT_RELATE[i].name) == 0)
      return ENT_RELATE[i];
  };

  return (EntityRelations){.count = 0};
}

static EntityInstance GetEntData(const char* name){
  for (int i = 0; i < NUM_ENTS; i++){
    if(strcmp(name, ENT_DATA[i].prefab) == 0)
      return ENT_DATA[i];
  };
}

static cam_d GetCamData(const char* name){
  for (int i = 0; i < NUM_CAMS; i++){
    if(strcmp(name, CAM_DATA[i].name) == 0)
      return CAM_DATA[i];
  };
}

static force_d GetForceData(const char* name){
  for (int i = 0; i < NUM_FORCES; i++){
    if(strcmp(name, FORCE_DATA[i].name) == 0)
      return FORCE_DATA[i];
  };
}

static phys_d GetPhysData(const char* name){
  for (int i = 0; i < NUM_PHYS; i++){
    if(strcmp(name, PHYS_DATA[i].name) == 0)
      return PHYS_DATA[i];
  };
}

static anim_d GetAnimData(const char* name){
  for (int i = 0; i < NUM_ANIM; i++){
    if(strcmp(name, ANIM_DATA[i].name) == 0)
      return ANIM_DATA[i];
  };
}

static stat_d GetStatData(const char* name){
  for (int i = 0; i < NUM_STATS; i++){
    if(strcmp(name, STAT_DATA[i].name) == 0)
      return STAT_DATA[i];
  };

}

#endif // SCENE_DATA_H
