// scene_data.h - GENERATED BY GM2 EXPORTER - DO NOT EDIT
#ifndef SCENE_DATA_H
#define SCENE_DATA_H

#include "scene.h"
#include "asset_resources.h"

#define NUM_SCENES  1
#define NUM_RES     2
// Scene Registry

static ResourceRef RESOURCES[NUM_RES] = {
  {RES_JSON, RES_ASEPRITE, RES_SPRITE, "resources/tile_sheet.json", "resources/tile_sheet.png", SHEET_TILE},
  {RES_JSON, RES_ASEPRITE, RES_ANIM, "resources/player-sheet.json", "resources/player-sheet.png", SHEET_CHAR}
};

static const SceneHeader SCENE_HEADERS[NUM_SCENES] = {
  {"stage_01", "resources/data/scenes/scene_01.json"}
};

#endif
