name: Web

on:
  push:
    branches:
      - "**"
  pull_request:

jobs:
  web:
    name: web
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Install build tools
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            cmake \
            ninja-build

      - name: Setup Emscripten
        uses: emscripten-core/setup-emsdk@v16
        with:
          version: 5.0.1

      - name: Configure
        run: emcmake cmake -S . -B build-web -G Ninja -DCMAKE_BUILD_TYPE=Debug -DPLATFORM=Web

      - name: Build
        run: cmake --build build-web --target index --parallel

      - name: Check artifacts
        run: |
          test -f build-web/index.html
          test -f build-web/index.js
          test -f build-web/index.wasm
          test -f build-web/index.data
